### ISSUE TITLE
Increase decay time

### ISSUE THREAD

**Issue by peastman** [sfzinstruments/SplendidGrandPiano#1]
I love this instrument.  It sounds beautiful and it's a joy to play.  The one thing I don't like about it is that it decays far too quickly.  You can only hold a note for a few seconds before the sound completely stops.  This is caused by these lines in the SFZ file.

```
ampeg_decay=40
ampeg_decay_oncc133=-20
```

There are a few problems with these lines:

1. There's no such thing as CC133.  CC numbers have to be between 0 and 127.  According to the official [MIDI implementation chart](https://www.midi.org/forms/midi_chart-v2.pdf), the recommended controller for decay time is 75.

2. The file provides a UI for setting release and veltrack, but not for decay time.

3. The values specified here are (in my opinion) too low.

Here is how I modified the header to fix these problems.  This makes the default decay time much longer, but it's now modifiable so if you really do want the fast decay you can still get it.

```
//midi cc
#define $RELEASE 72
#define $VELTRACK 99
#define $DECAY 75

//file-folder
#define $EXT flac
#define $DIR Data


//////////////////////////////////////////////////////////
<control>
default_path=Samples/

label_cc$RELEASE=Release
label_cc$VELTRACK=Veltrack
label_cc$DECAY=Decay
set_hdcc$RELEASE=0.35
set_hdcc$VELTRACK=1
set_hdcc$DECAY=0


//*******************************************************
<global>
ampeg_attack=0.0005
ampeg_hold=2
ampeg_hold_oncc$DECAY=-1
ampeg_decay=80
ampeg_decay_oncc$DECAY=-60
ampeg_sustain=0
ampeg_release_oncc$RELEASE=2
amp_veltrack_oncc$VELTRACK=-100
amp_veltrack_curvecc$VELTRACK=2
```

**Comment by kinwie** [comment]
Hello, glad you like the instrument.

CC133 is not a standard MIDI CC but it is an extended MIDI CC used by sfz for keyboard tracking. I didn't wired a Decay control to the UI on purpose. If you want to increase the decay, it is best to raise the value for it, e.g. :
```
ampeg_decay=80
ampeg_decay_oncc133=-60
```

And if you want to pop up the Decay control, can be like this, e.g. :
```
ampeg_decay=40
ampeg_decay_oncc$DECAY=40
ampeg_decay_oncc133=-40
```
Then set the hdcc to 1

Since this instrument already in sfz format, it is very easy to edit the text file. Feel free to modify to suit your personal taste.

**Comment by peastman** [comment]
Thanks, I already edited it to suite my personal taste.  I'm suggesting making these changes to the standard version so everyone can benefit from them.

What SFZ players support CCs above 127?  I can definitely confirm that Sforzando does not.  You can see this by going to the Controls tab.  If you set it to CC75, the Decay control appears.  Now change it to 133 and it disappears.  And since it isn't a standard MIDI CC, it's impossible to hook up a control on your keyboard or in your DAW to control it.  So why use a nonstandard, not widely supported CC instead of the standard, universally supported one?  And if you don't want to give the user control, why include the `ampeg_decay_oncc133` line at all?

As for the current default decay, it's just far too short.  Load the file into Sforzando, play a loud chord, and hold the keys down.  It takes only 4-5 seconds before it decays to the point of being mostly inaudible.  That's far faster than any real piano.

**Comment by kinwie** [comment]
Sforzando support the sfz extended MIDI CC. They are mostly not appears on the UI. CC133 is for keyboard tracking. So what in this instrument does, the decay time will linearly reduced from lokey to hikey (higher keys have shorter decay time).

Normally for full-length piano samples, we don't need to setting the decay. But this instrument has looped samples, so there's a need to shape the hold and decay. The one i used, ampeg_decay_oncc133, is for shaping the decay time globally across keyboard range.

I'll update the sfz later to increase the decay
Thanks for your suggestion

**Comment by kinwie** [comment]
I've made an update to the sfz in the repo, increasing hold and decay time. Also add a group_volume to each velocity layer for further user adjustment regarding velocity volumes.

**Comment by peastman** [comment]
That's a huge improvement.  Thanks so much!
