### ISSUE TITLE
String resonance

### ISSUE THREAD

**Issue by peastman** [sfzinstruments/SplendidGrandPiano#2]
This was an experiment that turned out very well.  I'm sharing it in case anyone else wants to try it.

A weakness in this instrument is that it has no string resonance.  Notes sound exactly the same whether the pedal is up or down.  On a real piano, holding down the pedal allows other strings to resonate with the overtones of the notes you play.  This creates a richer sound with more high frequencies.

I emulated this effect by mixing in a little bit of the PP sample for the note one octave up whenever the pedal is down.  It would be easy to extend this to include additional overtones, but even just including the first one makes a big difference.

The files are attached.  Resonance.txt goes in the Data folder.  I had to add .txt to the end of the SFZ file so Github would let me attach it.

[Splendid Grand Piano Res.sfz.txt](https://github.com/sfzinstruments/SplendidGrandPiano/files/5165441/Splendid.Grand.Piano.Res.sfz.txt)
[Resonance.txt](https://github.com/sfzinstruments/SplendidGrandPiano/files/5165442/Resonance.txt)

**Comment by kinwie** [comment]
Hi,
The string resonance sounds good. I include it into the main sfz and credit your name in the readme file, if you don't mind.
I did some tweak, tuning some high notes in the resonance mapping, and added a control for it to the UI.
Thanks for your nice addition!

**Comment by peastman** [comment]
That's excellent, thanks!
